// Generated by CoffeeScript 1.4.0
(function() {
  var cache;

  cache = {};

  window.Helpers = {
    polygon: {
      getStarPoints: function(centerX, centerY, arms, outerRadius, innerRadius) {
        var angle, currX, currY, i, r, results, _i, _ref;
        results = "";
        angle = Math.PI / arms;
        for (i = _i = 0, _ref = 2 * arms; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          r = (i & 1) === 0 ? outerRadius : innerRadius;
          currX = centerX + Math.cos(i * angle + angle) * r;
          currY = centerY + Math.sin(i * angle + angle) * r;
          if (i === 0) {
            results = currX + "," + currY;
          } else {
            results += ", " + currX + "," + currY;
          }
        }
        return results;
      },
      getPoints: function(centerX, centerY, arms, radius) {
        var angle, currX, currY, i, results, _i;
        results = "";
        angle = Math.PI * 2 / arms;
        for (i = _i = 0; 0 <= arms ? _i < arms : _i > arms; i = 0 <= arms ? ++_i : --_i) {
          currX = centerX + Math.cos(i * angle + angle / 2) * radius;
          currY = centerY + Math.sin(i * angle + angle / 2) * radius;
          if (i === 0) {
            results = currX + "," + currY;
          } else {
            results += ", " + currX + "," + currY;
          }
        }
        return results;
      }
    }
  };

  window.Helpers = Helpers;

}).call(this);
